/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: jdK3bL+r4njxy0sTH5NoQ3Du+/Cq+ORdbb0IcXk7EIAqGnk3urVJBOHyAOXjJH/KoI8SS3tqvnY1jG6TQ7SNrw==
 */

/* eslint-disable */
// tslint:disable

import Blocks, {Blocks_InsertParameters} from './blocks'
import Transactions, {Transactions_InsertParameters} from './transactions'
import TxIn, {TxIn_InsertParameters} from './tx_in'
import TxOut, {TxOut_InsertParameters} from './tx_out'

interface DatabaseSchema {
  blocks: {record: Blocks, insert: Blocks_InsertParameters};
  transactions: {record: Transactions, insert: Transactions_InsertParameters};
  tx_in: {record: TxIn, insert: TxIn_InsertParameters};
  tx_out: {record: TxOut, insert: TxOut_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}
