/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: gfQ05ClnLm23gWwMSne4dWpNEig80b3TDd3jmlJ4D4U8GLXmxx/j5pIQiXZm2j+cRop+zXn8W0T7tiqD/d8k9w==
 */

/* eslint-disable */
// tslint:disable

interface Transactions {
  hashBlock: unknown
  id: number & {readonly __brand?: 'transactions_id'}
  lockTime: number
  txid: unknown
  version: number
}
export default Transactions;

interface Transactions_InsertParameters {
  hashBlock: unknown
  id: number & {readonly __brand?: 'transactions_id'}
  lockTime: number
  txid: unknown
  version: number
}
export type {Transactions_InsertParameters}
