/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: oJ1n7VVv9yu0RHoB7QQjS4FBwLd9iNJ7nyJTW+mVI7sJDeq7i7Qx2WJQRL0hnYTKHNbEHGIxe/AaE5fhUKSoFw==
 */

/* eslint-disable */
// tslint:disable

interface TxIn {
  hashPrevOut: unknown
  id: number & {readonly __brand?: 'tx_in_id'}
  indexPrevOut: number
  scriptSig: unknown
  sequence: number
  txid: unknown
}
export default TxIn;

interface TxIn_InsertParameters {
  hashPrevOut: unknown
  id: number & {readonly __brand?: 'tx_in_id'}
  indexPrevOut: number
  scriptSig: unknown
  sequence: number
  txid: unknown
}
export type {TxIn_InsertParameters}
