/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Z6bnDa5/Nkk26f0QBJNt6wTOzKKwXzkiswv6lrG54wlPzPSGURUOxY6vi3PBtbJTfC1mmianPRtSOlfYH6K1VQ==
 */

/* eslint-disable */
// tslint:disable

interface TxOut {
  address: (string) | null
  id: number & {readonly __brand?: 'tx_out_id'}
  indexOut: number
  scriptPubKey: unknown
  txid: unknown
  /**
   * @default b'1'
   */
  unspent: unknown
  value: (string | number | BigInt)
}
export default TxOut;

interface TxOut_InsertParameters {
  address?: (string) | null
  id: number & {readonly __brand?: 'tx_out_id'}
  indexOut: number
  scriptPubKey: unknown
  txid: unknown
  /**
   * @default b'1'
   */
  unspent?: unknown
  value: (string | number | BigInt)
}
export type {TxOut_InsertParameters}
