/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: mXsbVt/MMXQA5DKT/VGGQs9ONgiskpS3lEHt3OUjjZ7qtSVRJOM7tuV4xdQhg+Zi80UURbqfsJw/qavyBT6s0g==
 */

/* eslint-disable */
// tslint:disable

interface Blocks {
  blocksize: number
  hash: unknown
  hashMerkleRoot: unknown
  hashPrev: unknown
  height: number
  id: number & {readonly __brand?: 'blocks_id'}
  nBits: number
  nNonce: number
  nTime: number
  version: number
}
export default Blocks;

interface Blocks_InsertParameters {
  blocksize: number
  hash: unknown
  hashMerkleRoot: unknown
  hashPrev: unknown
  height: number
  id: number & {readonly __brand?: 'blocks_id'}
  nBits: number
  nNonce: number
  nTime: number
  version: number
}
export type {Blocks_InsertParameters}
