/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: EUto1tPrwpMJmi8+hmX2pW+shXx/N5oXLJQSF8kZW5JRUi4aPPOV/Coit6lu6SUcPb+kE3x585XEnENOPFuJ4A==
 */

/* eslint-disable */
// tslint:disable

import Blocks from './blocks'

interface Transactions {
  hashBlock: Blocks['hash']
  id: number & {readonly __brand?: 'transactions_id'}
  lockTime: number
  txid: unknown
  version: number
}
export default Transactions;

interface Transactions_InsertParameters {
  hashBlock: Blocks['hash']
  id: number & {readonly __brand?: 'transactions_id'}
  lockTime: number
  txid: unknown
  version: number
}
export type {Transactions_InsertParameters}
