/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: gxZmwr3Jl150aSHrXaJenmPyj/i1tRp0jz5m4sK7ve4fKAwRGdNUodY9lWgn03GkRYVlyo6zBk2Say6iVl69KQ==
 */

/* eslint-disable */
// tslint:disable

import Transactions from './transactions'

interface TxOut {
  address: (string) | null
  id: number & {readonly __brand?: 'tx_out_id'}
  indexOut: number
  scriptPubKey: unknown
  txid: Transactions['txid']
  /**
   * @default b'1'
   */
  unspent: unknown
  value: (string | number | BigInt)
}
export default TxOut;

interface TxOut_InsertParameters {
  address?: (string) | null
  id: number & {readonly __brand?: 'tx_out_id'}
  indexOut: number
  scriptPubKey: unknown
  txid: Transactions['txid']
  /**
   * @default b'1'
   */
  unspent?: unknown
  value: (string | number | BigInt)
}
export type {TxOut_InsertParameters}
